name: Build and test

on:
  push:
    branches-ignore:
      - "master"

jobs:
  build-and-test:
    name: Build and teset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.19.1
      - name: Build docker and run tests
        run: ./scripts/dockerbuild-for-ci.sh
      - name: Finish job
        run: docker compose up --exit-code-from ui
